server:
  port: 7002

eureka:
  instance:
    hostname: eureka2.cn
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1.cn:7001/eureka/,http://eureka3.cn:7003/eureka/